### ISSUE TITLE
Error about DiceCoefficient Metrics

### ISSUE THREAD

**Issue by dajunC** [wolny/pytorch-3dunet#18]
Hi

When I use your code to run the random_label3D dataset, I find that if I change the 'loss' from 'ce' to 'dice' or the 'evel_metrics' from 'MeanIoU' to 'DiceCoefficient', it will happen the error like that:

```
 assert input.size() == target.size(), "'input' and 'target' must have the same shape"
AssertionError: 'input' and 'target' must have the same shape
```

Are there  something I didnt change?

**Comment by wolny** [comment]
Hi @dajunC,

in order train the network with DiceLoss on the sample `random_label3D.h5` one would need to change the model structure and data loaders. E.g. since Dice is a binary score the output from the network is just one channel (probability of the foreground). I uploaded a sample config for you to have a look (https://github.com/wolny/pytorch-3dunet/blob/master/resources/train_config_dice.yaml) and updated the README.

**Comment by dajunC** [comment]
Oh, Thank a lot!
I see the point.I really appreciate your help.
