### ISSUE TITLE
np.random generates the same random numbers for each data batch

### ISSUE THREAD

**Issue by Jiangchanglong1991** [wolny/pytorch-3dunet#32]
I used RandomRotate, RandomContrast and other transformers for data augmentation. I found out the angles in RandomRotate and brightness_factors in RandomContrast in each batch are the same, in other words, RandomRotate rotates images the same angle and RandonContrast clips images with the same factor every time.

When I set num_workers  in configuration files to 0, transformers work just fine. 

It seems like np.random generates the same random numbers for each data batch and it is an old issue in pytorch opened 2 years ago.

**Comment by shiqi1994** [comment]
for example, if write 'random(10)', that means you fix the seed 10. Once you fix the seed, you will generate the same number. I hope it may help :)

**Comment by wolny** [comment]
Hi @Jiangchanglong1991,
thanks for investigating the randomness in the augmentations. It's by design that workers return the same sequence of random numbers, since the workers share the common instance of the `Dataset` which was initialized with a fixed seed. I don't think it's a big issue though: if you have 4 workers they will all rotate the patch by the same angle, but the angle will change every 4 iterations.

> in other words, RandomRotate rotates images the same angle and RandonContrast clips images with the same factor every time.

is not correct. `RandomRotate` and `RandomContrast` variables will change every `num_workers` iterations.
